
version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/usr/src/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://ems_user:ems_pass@db:5432/ems
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: dev-secret-key
      RECAPTCHA_SITE_KEY: test-site-key
      RECAPTCHA_SECRET: test-secret

  worker:
    build: ./backend
    command: celery -A app.celery_worker.celery_app worker --loglevel=info -Q imports
    volumes:
      - ./backend/app:/usr/src/app/app
    depends_on:
      - backend
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://ems_user:ems_pass@db:5432/ems
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: dev-secret-key

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      REACT_APP_API: http://localhost:8000
      RECAPTCHA_SITE_KEY: test-site-key
    depends_on:
      - backend

volumes:
  db_data:
